### ISSUE TITLE
the language is an awesome idea but has unclear business model

### ISSUE THREAD

**Issue by klosworks** [seanbaxter/circle#10]
I just heard about Circle on cppcast and I must say I'm impressed. I hope It's not going to sound too much like I'm a know-it-all, but I'm going to suggest a change in business model. I don't know all the facts and I may get some things wrong, but I wanted to write this anyway, because I may have some ideas you can use.

The problem currently is that it's closed source and it could disappear any day, so I don't think people will take it seriously (I for sure wouldn't use it for commercial projects right now). I know it's a chicken and egg problem though (you may not get funding if you release the source).

Idea 1:

Why not make implementation open-source, build a community of users and then make money on consulting? It looks a bit like you are trying to repeat what Bjarne Stroustrup did, but it's not the 1980s anymore. 

Or maybe make the main language open-source and keep some tools (a non-essential one like a performance analyzer) paid?

Idea 2

In any case, I think you can learn a lot from the story of the D programming language. It is slowly gaining traction but its future is unclear because it has it's complications and it's not a big enough improvement over C++. An example of such feature is compile-time regex, but this is not important enough to make people switch languages.

A way for Circle to grow could be by creating a unique use case that could not be done easily in C++. Maybe see what Halide (https://halide-lang.org/) does, and see if you can replicate some or all of that with the compile-time magic of Circle. That could make you the king of HPC. 

Idea 3

One of the historical problems of D was a closed-source implementation. Some people just didn't want to work with such a tool. Also, even after open-sourcing it, the level of community contribution to the language itself was very small until the implementation began being hosted on Github. This is really important. There is always GNU GPL licence to use if you want to restrict commercial uses somewhat but I'm not sure how it would influence the behavior of the people you are pitching the language to.

**Comment by FROL256** [comment]
I agree with Artur! Do not think that I am trying to persuade you to open the source, this is entirely your decision.
But i would like to tell you my story shortly. 

In 2010 i was a student and decide to build production rendering system on GPU which implement some advanced light transport algorithms (Metropolis Light Transport and other). Well i did this with my colleagues http://www.raytracing.ru/  

But ... for more that 7 years during development  we don't have any commercial application (well, we had different support from research departments of university and RFBR due to we published a lot of research papers and because we were students this still was fun and great time).  

So we didn't have any commercial application until 2017 year because we had closed-source solution. When we opened all our source codes under MIT licence, on the very first conference (and not the most famous CG conference like Eurographics) we got customer from Saint-Petersburg lighting source manufacturer! Next 3 years we have different customers until Nvidia did their damn ray tracing chip ... but this is another story )

So, there are bunch of things i have understood from these 3 years of commercial application:

1) times have changed since 1990-2000 when it was possible to distribute closed source programs under Windows. No team will take a closed solution because for their production if problem happens, they can't fix it.

2) In fact, even for full Open Source they still can't fix bugs because your solution is complex. Therefore, they still cannot do without you. Customers honestly and in good faith will try to steal your solution and put their own programmers to support it without you. But they will fail in most cases. And in the end they will understand that working with you is simply cheaper than paying salary to their own developers which has another problems. This is the Open Source software model. Simple libraries like json parser can be just taken and used, but complex solution like compiler, operating system, HW or render are mandatory for support.

3) When you say that your solution is completely open source, it greatly increases your credibility. This is the first step towards getting a conversation with you. And if you do have community this increase your credibility 10 times from C to AA+ )

4) In fact, I began to understand that even when you do absolutely 100% custom work according to the customer's specifications, it does not mean that your customer will be able to use what you have done. Because the cost of supporting technically complex solutions is extremely high and thus many software projects just dying because funding is over and each next stage of development requires more and more efforts from developers due to growing complexity. So Open Source community may be the option but don't guarantee survival of the project.

5) In order to conclude a profitable deal for you with an investor and not loose all rights, you need to have a weighty argument to discuss your position. For example, 100 users and 10 customers is a powerful argument. Technological cool features - not, because investors do not understand this.

In any case, do not think that I am going to teach you, just sincerely wish you success because you project is just cool!

**Comment by seanbaxter** [comment]
There are lots of open source compilers. If that model is so good, get a Clang or gcc fork to do this.

**Comment by FROL256** [comment]
Sean, thank you very much for the reply!  
I would be very grateful if you reply to this issie also
https://github.com/seanbaxter/shaders/issues/6

**Comment by seanbaxter** [comment]
> Sean, thank you very much for the reply!
> I would be very grateful if you could find a time to reply to this issie also
> [seanbaxter/shaders#6](https://github.com/seanbaxter/shaders/issues/6)
> 
> Thanks!

Yup, just commented on that.

**Comment by FROL256** [comment]
Sorry, still don't see your answer there for some reason. Don't know why probably it is a bug of github?

**Comment by klosworks** [comment]
> 
> 
> There are lots of open source compilers. If that model is so good, get a Clang or gcc fork to do this. The honest truth is that an unfunded, unsupported open source project of this size would certainly fail. I could not keep making constant upgrades to the system while also trying to onboard contributors who in the end wouldn't really contribute much. That requires a management level, code review, actual staffing. If I can interest a company in supporting then open source is a viable long-term model, but I don't see it working for me now.

Well, given that the project is large, if you have few users and just work on the language on your own, it won't work either.

One way to get contributors is to have a killer use case that will convince people to switch to Circle. (Whether they come to a project that is closed-source is another issue but let's shelve this one for now).

I think you've invented some good use cases and described them on https://github.com/seanbaxter/circle
I'm not sure if the use cases are good enough for people to switch to Circle (I have no time to get into them now), but they seem very cool at the first glance.
I don't think the descriptions are compelling enough though.

The typical pattern you have is
* a long paragraph describing the problem statement
* some tutorial-like code samples to get people started
* more samples

To boost engagement, I think that you could have:
* one catchy phrase, framing Circle as a replacement of some other tool (a language or a library that you intend to displace) for the described use case
* side-by-side comparison of the code in Circle and the other tool
* textual description of advantages and disadvantages of Circle
* a link to the old tutorial page

This would not only provide a more clear statement of the level of improvement that Circle provides, but also show that you've done your homework and really understood what it's like to use the state-of-the-art tools for the given problems.

I think the "What is Circle" could also use an improvement. Now you have

```
Circle is a new programming language that extends C++ 17 to support data-driven imperative metaprogramming. 
```
This is a good definition for programming languages experts but most people aren't them. I think you may be losing most incoming people at the point, because they aren't convinced that metaprogramming is something that they need. And you are even suggesting that you don't even enhance all the metaprogramming but only the data-driven imperative kind. Importantly, at this point you are losing some investors and managers because they no longer believe that you can explain the advantages of Circle in a way that can be understood quickly.

My advice is to perhaps keep the `Circle is a new programming language that extends C++ 17 to `  part and then insert a real use case or some general terms that every programmer would understand. 

Then, there is still the issue of people being afraid to implement projects based on a piece of tech that is closed and may die any time. But perhaps if you convinced some investor and got some employees, this fear could go away even for a closed-source project.
