### ISSUE TITLE
Uninformative "error: translation aborted"

### ISSUE THREAD

**Issue by Dann239** [seanbaxter/circle#119]
Hi! I decided to try out Circle and i stumbled upon something strange.

To illustrate, let's consider this code:
```cpp
@meta void foo() {
    static_assert(false);
}

int main() {
    foo();
}
```

Now, when i try to compile it, i get the following output:
```
$ ./circle test.cpp 
error: translation aborted; too many errors
```

and that's it. There's no diagnostic of any kind, and if it happened in a more complicated piece of code (which it did, initially), it would be very difficult to figure out where exactly i messed up.

Perhaps it is a known limitation? If so, i apologize

**Comment by seanbaxter** [comment]
I should probably error on @meta function declarations. I can't recall what the original semantics of that were supposed to mean. I think it was to allow passing of compile-time function parameters, but that avenue only led to sadness. 

@meta object declarations are fine. Basically, for now, don't declare @meta functions. Write normal functions and use @meta to execute them at compile time. The error message got truncated because this kind of code path is never really tested.

**Comment by Dann239** [comment]
thanks!
