### ISSUE TITLE
destructor member of global of templated class never instantiated

### ISSUE THREAD

**Issue by DaemonSnake** [seanbaxter/circle#29]
```c++
#include <cstdio>

template<class T>
struct child {
    ~child() {
        @meta std::printf("Never called\n");
    }
};

template<class T>
child<T> dep = {};

static_assert(sizeof(dep<int>));
```

**Comment by seanbaxter** [comment]
I think the issue is that variable templates like `dep` require ODR usage to be instantiated. Consider this:
https://godbolt.org/z/danGTGfvY
```cpp
#include <cstdio>

template<class T>
struct child {
  child() { 
    @meta printf("Generting ctor\n");
    printf("Ctor called\n"); 
  }
  ~child() {
    @meta printf("Generating dtor\n");
    std::printf("Dtor called\n");
  }

  int x;
};

template<class T>
child<T> dep = {};

int main() {
  // Variable templates have inline linkage.
  // You must ODR use a variable template to cause its instantiation.
  dep<int>.x = 100;
}
```

By using the variable template in main, it gets instantianted and its ctors and dtors are generated. `sizeof` will make the type complete, which instantiates its definition, but it doesn't force the instantiation of its ctor or dtor definitions.

I don't think this is a bug, and you can compare clang's behavior to see the same thing.

**Comment by DaemonSnake** [comment]
Hello!
Thanks for your answer.

It seems, in trying to simplify my code, I messed the example up and removed the core of the issue.

I have reworked it and put it in comparison with what happens with GCC,CLANG, MSVC and ICC

The example is as follows:
```c++
template<class>
constexpr bool always_false = false;

template<class T>
struct dep {
    struct type
    {
        type() {
            static_assert(always_false<T>);
        }
    };

    static inline const auto var = type{}; //auto here is likely the issue
};

static_assert(sizeof(dep<int>::var));
```

For GCC,CLANG, MSVC and ICC this piece of code fails to compile:
https://godbolt.org/z/r3GGrx8cT

Whiste for Circle dep<int>::type::type is never instantiated:
https://godbolt.org/z/a687o1sqM

**Comment by seanbaxter** [comment]
This is very interesting. I... will have to study the C++ Standard to figure this out. Is var automatically initialized when named inside the sizeof? That's a good question.

**Comment by DaemonSnake** [comment]
It's a really weird corner case.
Even worse, It appears that the constructor is only instantiated at the end transition unit by most compilers.
We can verify this by adding a `static_assert(false)` at the end of the example. 
godbolt: https://godbolt.org/z/cMz9Y8YGq

It would seem that the sizeof triggers the definition of the 'type' structure but that the variable is itself only initialized in a cleanup phase at the end of the translation unit, triggering itself the instantiation of type's constructor

**Comment by seanbaxter** [comment]
What context did you encounter this in? Is the code available?

**Comment by seanbaxter** [comment]
https://godbolt.org/z/nPPeoxKc8

Externally defining the static member object _doesn't_ trigger the failure on major compilers. So.. I guess because it's inline? This is an obscure corner.

**Comment by DaemonSnake** [comment]
> Externally defining the static member object _doesn't_ trigger the failure on major compilers. So.. I guess because it's inline? This is an obscure corner.

I managed to reproduce via variable-template + auto instead of dependent + static inline

```c++
template<class>
constexpr bool always_false = false;

template<class T>
struct dep {
    dep() {
        static_assert(always_false<T>);
    }
};

template<class T>
const auto var = dep<T>{};

static_assert(sizeof(var<int>));
```
godbolt: https://godbolt.org/z/jjd5bqhhe

If we replace auto with `dep<T>` then the ctor is now never instantiated (except for ICC): https://godbolt.org/z/rr15z7fKa

> What context did you encounter this in? Is the code available?
I found this will messing around with a follow up to my unconstexpr project.

**Comment by dfrib** [comment]
I believe this is ill-formed NDR in the current draft, as per [[temp.res.general]/6.4](https://eel.is/c++draft/temp.res.general#6.4) of the current draft:

> The validity of a template may be checked prior to any instantiation.
> 
> The program is ill-formed, no diagnostic required, if:
> - [...]
> - a hypothetical instantiation of a template immediately following its definition would be ill-formed due to a construct that does not depend on a template parameter, or [...]

Previously likely under-specified as per [CWG1253](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#1253).

**Comment by seanbaxter** [comment]
> The validity of a template may be checked prior to any instantiation.

The mainstream compilers don't produce an error until `dep` is actually specialized by the specialization of the `var` alias template. There's no "hypothetical instantiation" going on. I don't think they are implementing that language, and I think a lot of code would break if vendors did so.

What is drawing my attention is the use of the default constructor in the alias template declaration. The usage of `var<int>` in the _sizeof-expression_ is causing that specific ctor to be instantiated. To my mind, that seems like ODR usage, but from an unevaluated context.

So I figure, maybe I need to basically substitute the initializer of the alias template into the sizeof, so that the ctor call { } will be visible: eg `sizeof(decltype(dep<int> { }))`

```cpp
template<class>
constexpr bool always_false = false;

template<typename T>
struct foo_t {
  foo_t() { 
    static_assert(always_false<T>);
  }

  int x;
};

int main() {
  int x = sizeof(decltype(foo_t<int>{ }));
  int y = sizeof(foo_t<int>{ });
}
```

However, this actually compiles just fine on gcc and clang! No ctor is being generated, even though I'm explicitly calling it in two different ways. So, why is it being instantiated when there is the indirection of an alias template?

**Comment by dfrib** [comment]
> However, this actually compiles just fine on gcc and clang! No ctor is being generated, even though I'm explicitly calling it in two different ways. So, why is it being instantiated when there is the indirection of an alias template?

It seems that `auto` type deduction is essential here. As @DaemonSnake highlighted the specialization is instantiated only if the variable template use `auto` type deduction.
```
// Compilers accepts use of `var_t<T>` in unevaluated contexts
template<class T>
const foo_t<T> var_t = foo_t<T>{};

// Compiler rejects ...
template<class T>
const auto var_t = foo_t<T>{}; // OK to use `var_t<T>` in unevaluated contexts
```
We see the same behavior also if we indirect via a class template value wrapped instead of a variable template:
```
// ^^^ foo_t made into a literal type

// Compiler accepts use of `Var<T>::value` in unevaluated contexts
template<typename T>
struct Var {
    static constexpr foo_t<T> value{foo_t<T>{}};
};

// Compiler rejects
template<typename T>
struct Var {
    static constexpr auto value{foo_t<T>{}};
};
```

[\[temp.inst\]/11](https://eel.is/c++draft/temp.inst#11) clearly requires implementors to not instantiate `var_t` unless required:

> An implementation shall not implicitly instantiate [...] a variable template [...] unless such instantiation is required. 

I haven't been able to find why `auto` type deduction of a variable declaration would require instantiating the definition of entities in the variable's initialization expression, but the wording is quite clear that this is required e.g. for `auto` return type deduction (which makes sense), as per [\[dcl.spec.auto.general#\]](https://eel.is/c++draft/dcl.spec.auto.general#12):

> [...] [Note 3: Therefore, **any use** of a specialization of the function template will cause an implicit instantiation. [...] ]

Could the `auto` for some reason mean that [\[expr.const\]/15](http://eel.is/c++draft/expr.const#15):

> expr.const/14 [Note 7: A manifestly constant-evaluated expression is evaluated even in an unevaluated operand. — end note]

applies such that the variable is needed for constant evaluation, such that [\[temp.inst\]/8](https://eel.is/c++draft/temp.inst#8) in turn implies that the existence of the definition affects the semantics of the program?

> The existence of a definition of a variable [...] is considered to affect the semantics of the program if the variable [...] is needed for constant evaluation by an expression ([expr.const]), even if constant evaluation of the expression is not required or if constant expression evaluation does not use the definition.

In turn instantiating it as per [\[temp.inst\]/2](https://eel.is/c++draft/temp.inst#2)?

**Comment by DaemonSnake** [comment]
Hi,
It seems to me that it has morphed into a standard question instead of an implementation one.
I’ll keep checking and if I find something I’ll report it here.
Thanks ^^
