### ISSUE TITLE
circle: "definition for @codegen object __nvvm_current_device_sm not available"

### ISSUE THREAD

**Issue by jaredhoberock** [seanbaxter/circle#57]
The following program

```
#include <iostream>

constexpr bool is_host()
{
  bool result = true;

  if target(__nvvm_current_device_sm)
  {
    result = false;
  }

  return result;
}

int main()
{
  if constexpr(is_host())
  {
    std::cout << "main on host" << std::endl;
  }

  return 0;
}
```

Causes circle to emit the error message

```
$ circle --cuda-path=/usr/local/cuda -sm_60 repro.cu 
function call: repro.cu:17:23
error during call to bool is_host()
  function declared at repro.cu:3:16
  if constexpr(is_host()) 
                      ^
  error: repro.cu:7:13
  definition for @codegen object __nvvm_current_device_sm not available
    if target(__nvvm_current_device_sm) 
```

Compiler details:

```
$ ~/Desktop/circle/circle --version
circle version 1.0.0-140
  Circle public preview build 140
  Built Oct 21 2021 17:21:34
  (c) 2021 Sean Baxter
  https://www.circle-lang.org/
  Twitter: @seanbax
```

**Comment by seanbaxter** [comment]
I will implement the C++23 feature _if-consteval_ soon.. It helps with this issue.

At the same time, I'm rather scared that you wrote a `constexpr bool is_host()` function. I feel better that it doesn't compile. I can't determine if it breaking indicates a bug or not. I will add an `__is_host` codegen object that evaluates true when lowering to x86 and false when lowering to PTX/SPIR-V/DXIL. 

```cpp
__global__ void func() {
  if constexpr(is_host()) { asm("intel asm here"); }
  else { asm("PTX here"); }
}
```

By defining a constexpr is_host and using it in an if-constexpr statement, you can break things. Here we're clearly in device code, but if Circle were to indicate 0 for `__nvvm_current_device_sm` during constexpr evaluation, we'd emit the Intel code branch rather than the PTX code branch. The _if-target_ mechanism defers branch selection until we're actually lowering code to a specific target.

C++20's `std::is_constant_evaluated` is a huge footgun for this reason. _if-consteval_ is essentially an _if-target_ with an `__is_constexpr` condition. 

There is an argument that these codegen objects should be defined during constant evaluation... Not all uses are nefarious. 

Can you provide more context as to what you want to achieve? I'm fine changing the compiler to address your issues, but I don't want to make changes that make users' code buggier.

**Comment by jaredhoberock** [comment]
What is the objection to `constexpr is_host`?

**Comment by seanbaxter** [comment]
![Screenshot at 2021-10-29 17-19-02](https://user-images.githubusercontent.com/521513/139502898-34e078f9-042d-4bd9-ab73-766b99c0ea2b.png)
(P1938)[http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1938r2.html] shows the same abuse of _if-consteval_ that you committed with _if-target_. The authors think it's a valid case. Although, again, it does re-invent the `if constexpr(std::is_constant_evaluated())` footgun.

**Comment by jaredhoberock** [comment]
I don't understand. What's the problem? Is the code you posted supposed to be a good thing or a bad thing?

**Comment by seanbaxter** [comment]
> What is the objection to constexpr is_host?

See this description of the problem:
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1938r2.html#the-if-constexpr-stdis_constant_evaluated-problem

`if constexpr(std::is_constant_evaluated())` is ALWAYS true. `std::is_constant_evaluated()` is a constexpr function that returns true or false. Evaluating it in a constexpr context yields true, so that true branch is always taken. The error was making it a `constexpr` function. It should have been a "codegen" object like `__nvvm_current_device_sm`, but C++20 didn't have any mechanism like that.

`if constexpr(is_host())` falls into the identical trap. That is ALWAYS true. If you use it inside a function that may be lowered to PTX, it's just going to mislead the compiler, by indicating you're generating host code rather than device code.

**Comment by seanbaxter** [comment]
I think _if-target_ inside constexpr functions is okay. There are good uses for that. But when you return the value of the _if-target_ predicate out of the constexpr function, then you allow it to be used from _if-constexpr_ statement's predicate, which is not okay!

**Comment by seanbaxter** [comment]
The way forward is for you to tell me what you want to achieve, and I'll put in a mechanism that does that without becoming another footgun.

**Comment by jaredhoberock** [comment]
> But when you return the value of the if-target predicate out of the constexpr function, then you allow it to be used from if-constexpr statement's predicate, which is not okay!

Then if-target is broken :-(

Anyway...

> Can you provide more context as to what you want to achieve? 

I have a few functions like this I need so far:

```
constexpr bool is_host()
{
  bool result = true;

#if defined(__CUDACC__)
  if target(__nvvm_current_device_sm)
  {
    result = false;
  }
#endif

  return result;
}


constexpr bool is_device()
{
  return !is_host();
}


constexpr bool has_cuda_runtime()
{
  bool result = false;


#if defined(__CUDACC__)
  if constexpr(is_host())
  {
    // XXX we could consider using #__has_include(<cuda_runtime_api.h>) here
    result = true;
  }
  else if target(__nvvm_arch >= nvvm_arch_t{35})
  {
#if defined(__CUDACC_RDC__)
    // in __device__ code, using the CUDA Runtime requires relocatable device code
    result = true;
#endif
  }
#else
  result = true;
#endif

  return result;
}
```

I will probably need more along these lines. I'd like to seal use of non-standard stuff like if-target inside things that look like standard C++ (such as if constexpr, or if consteval or whatever).

**Comment by seanbaxter** [comment]
> Then if-target is broken :-(

_if-target_ isn't broken. I can add a codegen object `__is_host`. But that would not be usable from inside an _if-constexpr_ predicate.

What you want is a chain of _if-target_ statements:
```cpp
if target(__is_host) { 
} else if target((int)__nvvm_arch >= 35) { 
} else {
}
```

We can't allow _if-constexpr_ anywhere here, because they'll evaluate incorrectly. We don't know what we're targeting until lowering, but _if-constexpr_ is evaluated during instantiation.

_if-target_ is doing the right thing here. You keep trying to use something that's not available until lowering at the point of instantiation. I'm trying to prevent that from happening, because it's wrong. You can't have a `constexpr has_cuda_runtime()` function. The compiler can't know if it's targeting CUDA during constexpr evaluation, so the better thing to do is to break rather than to give you the wrong answer.

**Comment by jaredhoberock** [comment]
When can the compiler know if it's targeting CUDA?

**Comment by seanbaxter** [comment]
> When can the compiler know if it's targeting CUDA?
It knows inside _if-target_'s predicate. That predicate is evaluated during lowering, when you know if it's x86, PTX, SPIR-V or DXIL. The _if-constexpr_ predicate is evaluated during template instantiation, which is before lowering to a target. 

There's a very good argument that you also know during constexpr evaluation: I know I'm not literally running a constexpr function on the GPU, or inside a shader. I could definitely define and set `__nvvm_current_device_sm = 0` then. But then if you return that state from a constexpr function, and you can `if-constexpr` on it, and get the wrong thing. It'll report that you're always on the host, even when you're not.

> Can any information escape an if-target branch?
The question is "can any _constexpr_ information escape an if-target branch." The `if-consteval` proposal says yes. They lets you implement a constexpr `is_constant_evaluated`, but then you can step right into the trap that they describe in [3.2](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1938r2.html#the-if-constexpr-stdis_constant_evaluated-problem). 

But I would like to avoid the user trapping themselves, because that's harder to diagnose than a compiler error like you're getting right now.

I'd like to know what effect you want, and add in mechanism to achieve that which is more robust against well-intentioned misuse.

**Comment by seanbaxter** [comment]
I think the best way forward is for me to implement _if-consteval_. I'll leave the NVVM stuff undefined during constexpr evaluation. You can then implement `constexpr is_host` like you did, but you'd have to use _if-consteval_ to do that, not my _if-target_ mechanism. That way, any misuse will be documented and understood with respect to this Standard C++23 feature, and not thought of as a defect having to do with targeting CUDA. It's a general phenomenon you're dealing with.

**Comment by jaredhoberock** [comment]
I don't understand the issues involved, but your proposed resolution sounds good to me.

**Comment by seanbaxter** [comment]
https://gist.github.com/seanbaxter/c95e89f3294edf9fa6b999fca8cb5ed2

How does this look? You can keep a `constexpr bool is_host` function, but just don't call it from an if-constexpr statement. I've modified the compiler so you can call it from an if-target statement.

You'll see that the constexpr bar function calls this from a normal if-statement. This should also work as expected. constexpr uses of bar will return 1, since if-consteval is entered. Non-constexpr uses of bar will return 2 (when called during lowering to the host module) or 3 (when called during lowering to the device module).

**Comment by jaredhoberock** [comment]
A constexpr function that isn't allowed to be called from an if constexpr? Isn't that a little confusing?

Could is_host be made a consteval function callable from an if consteval?

**Comment by seanbaxter** [comment]
> A constexpr function that isn't allowed to be called from an if constexpr? Isn't that a little confusing?
Welcome to C++ in the 2020s. This is why compiler people are always complaining about std::is_constant_evaluated. It's very easy to misuse.

> Could is_host be made a consteval function callable from an if consteval?
That would be much worse. A `consteval` function is _always_ evaluated at compile time. The _if-constexpr_ mechanism uses a delayed predicate evaluation, just like _if-target_. The use of _consteval_ in functions vs _if-consteval_ kind of mean the opposite thing! 

> So using it with a normal if wouldn't make sense for me.
Use it inside an _if-target_. Always use _if-target_!

I feel like I did wrong by even defining a `constexpr` function in that gist. Really you should use _if-consteval_ and _if-target_ everywhere you want to switch. Don't write `constexpr` functions.

```cpp
if consteval {
  // constexpr stuff here
} else if target(__is_host_target) {
  // x86-64 code here
} else if target(__nnvm_current_device_sm) {
  // PTXAS
} else if target(__is_spirv_target) {
   // Vulkan and OpenGL
} else if target(__is_dxil_target) {
  // Direct3D 12
}
```

Just like this!

**Comment by seanbaxter** [comment]
if-consteval is in Build 141. See the updated CUDA reflection section for usage notes. 
https://github.com/seanbaxter/circle/tree/master/cuda#reflection-and-if-target
